---
# This is the top-level playbook that will set up your server with all currently available software.
# See the Docs for information on how to run selected parts only.

- hosts: all
  user: deploy
  sudo: True
  vars_files:
    - vars/vars.yml

  roles:
    #- common
    #- blog
    #- mysql
    #- redmine
    #- gogs
    - piwik
