---
# Set up MySQL via docker

- name: Get tutum-docker-mysql repo from GitHub
  git: repo=https://github.com/tutumcloud/tutum-docker-mysql.git dest=/home/deploy/tutum-docker-mysql/
  register: mysqlrepoupdated

- include: mysql-build.yml
  when: mysqlrepoupdated.changed == True

- name: Ensure MySQL is started
  docker:
    image: tutum/mysql
    name: mysql
    ports: 3306:3306
    env:
      MYSQL_PASS: "{{ mysql_admin_password }}"
    volumes: /mnt/mysql:/var/lib/mysql
    state: running
