---
# Install main packages

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-dates" state=absent

- name: Install required software packages
  apt: pkg={{ item }} state=installed
  with_items:
  - git-core
  - build-essential
  - python-software-properties
  - g++
  - make
  - htop
  - iftop
  - iotop
  - htop
  - vim-nox
  - subversion
  - mercurial
  - bzr
  - python-pycurl
  - screen
  - curl

- name: Add nginx ppas
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:nginx/stable

- name: Update APT package cache
  apt: update_cache=yes

- name: Install main packages for python and nginx
  apt: pkg={{ item }} state=installed
  with_items:
    - libfreetype6
    - libfreetype6-dev
    - libjpeg62
    - libjpeg62-dev
    - libpq-dev
    - libxml2-dev
    - nginx
    - python-dev
    - python-imaging
    - python-setuptools
    - zlib1g-dev
    - python-mysqldb
    - openssl
